id: redhat.rhamt-vscode-extension
version: 0.0.6
type: VS Code extension
name: RHAMT Extension
title: RHAMT Extension
description: Application migration and modernization using the Red Hat Application Migration Toolkit (RHAMT)
url: https://download.jboss.org/jbosstools/adapters/stable/rhamt-vscode-extension/rhamt-vscode-extension-0.0.6-120.vsix
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
publisher: Red Hat, Inc.
repository: https://github.com/windup/rhamt-vscode-extension
category: Other
firstPublicationDate: "2019-06-19"
attributes:
  extension: "vscode:extension/redhat.rhamt-vscode-extension"
  containerImage: "johnsteele/rhamt-vscode-extension:latest"